param(
  [string] $BuildDir = "build-release-codex",
  [string] $McpExe = "",
  [string] $ServerName = "trenchbroom",
  [string] $OutputDir = "",
  [switch] $Print
)

$ErrorActionPreference = "Stop"

function ConvertTo-PrettyJson {
  param([object] $Value)

  return $Value | ConvertTo-Json -Depth 64
}

function Escape-TomlString {
  param([string] $Value)

  return $Value.Replace("\", "\\").Replace('"', '\"')
}

if ([string]::IsNullOrWhiteSpace($McpExe)) {
  $McpExe = Join-Path $BuildDir "app\TrenchBroomMcp\trenchbroom-mcp.exe"
}

if (-not (Test-Path $McpExe)) {
  throw "MCP executable not found: $McpExe. Build target trenchbroom-mcp first."
}

$resolvedMcpExe = (Resolve-Path $McpExe).Path

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
  $OutputDir = Join-Path $BuildDir "mcp-config"
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$resolvedOutputDir = (Resolve-Path $OutputDir).Path

$mcpServer = [ordered] @{
  command = $resolvedMcpExe
  args = @()
}

$mcpServers = [ordered] @{
  mcpServers = [ordered] @{
    $ServerName = $mcpServer
  }
}

$genericConfig = [ordered] @{
  name = $ServerName
  command = $resolvedMcpExe
  args = @()
  transport = "stdio"
  notes = @(
    "Start TrenchBroom first.",
    "Enable MCP in TrenchBroom preferences and use ReadOnly or Edit mode.",
    "Run scripts\\mcp-smoke.ps1 to verify the local bridge."
  )
}

$codexToml = @"
[mcp_servers.$ServerName]
command = "$(Escape-TomlString $resolvedMcpExe)"
args = []
"@

$genericPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.generic.json"
$mcpServersPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.mcpServers.json"
$codexPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.codex.toml"
$readmePath = Join-Path $resolvedOutputDir "README.md"

Set-Content -Path $genericPath -Value (ConvertTo-PrettyJson $genericConfig)
Set-Content -Path $mcpServersPath -Value (ConvertTo-PrettyJson $mcpServers)
Set-Content -Path $codexPath -Value $codexToml

$readme = @"
# TrenchBroom MCP Client Config

Generated by `scripts\mcp-config.ps1`.

## Files

- `trenchbroom-mcp.generic.json`: Generic stdio MCP server record.
- `trenchbroom-mcp.mcpServers.json`: JSON snippet for clients that use an `mcpServers` object, such as Claude Desktop / Cursor style configs.
- `trenchbroom-mcp.codex.toml`: TOML snippet for Codex-style MCP config.

## Server

Name: `$ServerName`

Command:

```text
$resolvedMcpExe
```

## Before Connecting

1. Start TrenchBroom.
2. Enable MCP in TrenchBroom preferences.
3. Use `ReadOnly` for inspection or `Edit` for map-changing tools.
4. Run:

```powershell
scripts\mcp-smoke.ps1 -RawJson
```

If the smoke script reports `Forbidden`, TrenchBroom MCP mode is still `Off`.
"@

Set-Content -Path $readmePath -Value $readme

Write-Host "MCP executable: $resolvedMcpExe"
Write-Host "Output directory: $resolvedOutputDir"
Write-Host "Generated:"
Write-Host "  $genericPath"
Write-Host "  $mcpServersPath"
Write-Host "  $codexPath"
Write-Host "  $readmePath"

if ($Print) {
  Write-Host ""
  Write-Host "mcpServers JSON:"
  Get-Content -Path $mcpServersPath
  Write-Host ""
  Write-Host "Codex TOML:"
  Get-Content -Path $codexPath
}
